# name of the instrument server that the client will use to connect
# ip address of the instrument server as seen by the client
# port to run the RPyC instrument server on
server_settings:
  name: 'local1'
  ip: 'localhost' # only allow client connections from the same machine
  # ip: '192.168.0.15' # use a local network static ip for remote clients
  port: 5556

# address of the mongodb server
mongodb_addr: 'mongodb://localhost:27017/'

# this list will be used by the instrument server to automatically load 
# the specified devices - the syntax is:
#   device_name:
#     class: 'device class'
#     args: [<*args>]
#     kwargs: {<**kwargs>}
devices:
  fake_sg:
    class: lantz.drivers.examples.LantzSignalGenerator
    args: [TCPIP::localhost::5678::SOCKET]
    kwargs: {}
  fake_osc:
    class: lantz.drivers.examples.dummydrivers.DummyOsci
    args: []
    kwargs: {}
