# address of the mongodb server
mongodb_addr: 'mongodb://localhost:27017/'

# configuration of the instrument servers you want to be accessible 
# from the instrument manager
instrument_servers:
  local1: {address: 'localhost', port: 5556}
#  remote1: {address: '192.168.1.10', port: 5556}

# devices accessible from spyrelets
devices:
  my_sg1: {server_id: 'local1', server_device: 'fake_sg'}
  my_osc1: {server_id: 'local1', server_device: 'fake_osc'}
#  my_sg2: {server_id: 'remote1', server_device: 'sg'}

# Experiment list
# Each experiment entry should have an
# alias:
#   class: 'spyrelet class'
#   spyrelets: A dictionary containing the sub-spyrelet to be used
#   args: Argument used to instanciate the spyrelet.  This included device alias dict, spyrelets dict and other CONSTS parametters
experiments:
  s2:
    class: nspyre.user.test_spyrelets.SubSpyrelet
    args:
      device_alias: {sg: 'my_sg1'}

  my_exp:
    class: nspyre.user.test_spyrelets.MyExperiment
    spyrelets: {s2: s2}
    args: {device_alias: {sg: 'my_sg1', osc: 'my_osc1'}}
