
# Here are all the setting which will be used by default by the various parts of NSpyre
# The user should modify these to suit their specific configuration

# Addresses of the one of the mongodb server in the replica set.
mongodb_addr: mongodb://localhost:27017/

# This is the name of the replica set for the mongodb servers (this should match the _id given during the rs.initialize command)
replica_set_name: NSpyreSet

# This is the addrs of the instrument servers you want to include in the instrument manager
instrument_servers_addrs:
  # - {ip: 192.168.1.112, port: '5556'}
  - {ip: localhost, port: '5556'}

# These will be used when a instrument server is instanciated on this computer
instrument_server:
  server_name: Experiment_Computer
  port: 5556

# Device list
# This list will be used to instanciate the instrument server automatically when it is launched 
# Each device should have an
#   alias:
#     - 'device class'
#     - [<*args>]
#     - {<**kwargs>}
device_list:
  my_sg:
    - lantz.drivers.examples.LantzSignalGenerator
    - [TCPIP::localhost::5678::SOCKET]
    - {}
  osc:
    - lantz.drivers.examples.dummydrivers.DummyOsci
    - []
    - {}
# Experiment list
# Each experiment entry should have an
# alias:
#   - 'spyrelet class',
#   - device alias dict (This can be empty if all the device have the same name in the spyrelet code and in the instrument server)
#   - required spyrelets dict
experiment_list:
  my_exp:
    - nspyre.user.test_spyrelets.MyExperiment
    - {sg: my_sg, osc: osc,}
    - {s2: sub_spyrelet}
  sub_spyrelet:
    - nspyre.user.test_spyrelets.SubSpyrelet
    - {sg: my_sg,}
    - {}


# Experimental State
# This is a list parametters which should be saved along with the data
experimental_state:
  device_feat:
    mw_freq: [my_sg, frequency]
    mw_ampl: [my_sg, amplitude]
  device_dictfeat:
    # res_freq: [ws7, wavelength, 0]
  

